package(default_visibility = ["//visibility:public"])

filegroup(
    name = "linux",
    srcs = glob(
        include = ["**"],
        exclude = ["BUILD"],
    ),
    visibility = ["//prebuilts/studio/layoutlib:__subpackages__"],
)
