package(default_visibility = ["//visibility:public"])

filegroup(
    name = "fonts",
    srcs = glob(
        include = ["*"],
        exclude = ["BUILD"],
    ) + [
        "native/fonts.xml",
    ],
)
