exports_files(srcs = ["framework_res.jar"])

# managed by go/iml_to_build
java_import(
    name = "layoutlib",
    jars = ["layoutlib.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "layoutlib_native",
    jars = ["layoutlib_native.jar"],
    visibility = ["//visibility:public"],
)
